### ISSUE TITLE
I can not add to Android Studio Project

### ISSUE THREAD

**Issue by joramkimata** [ar-android/DrawRouteMaps#3]
Hey

when i added to gradle build i got the following error, please assist
![error](https://user-images.githubusercontent.com/4988463/27470355-39aaab88-57fc-11e7-80a4-ff386e27e62e.PNG)

**Comment by ar-android** [comment]
Have you added the maven url
```gradle
allprojects {
   repositories {
	maven { url "https://jitpack.io" }
   }
}
```
